[project]
name = "codecraft-journey"
version = "0.1.0"
description = "A coder's travelogue: Solving puzzles, one algorithm at a time."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
]
